	
        _______           
    .adOOOOOOOOOba.
   dOOOOOOOOOOOOOOOb
  dOOOOOOOOOOOOOOOOOb
 dOOOOOOOOOOOOOOOOOOOb
|OOOOOOOOOOOOOOOOOOOOO|
OP'~"YOOOOOOOOOOOP"~`YO
OO     `YOOOOOP'     OO
OOb      `OOO'      dOO
YOOo      OOO      oOOP
`OOOo     OOO     oOOO'
 `OOOb._,dOOOb._,dOOO'
  `OOOOOOOOOOOOOOOOO'
   OOOOOOOoOoOOOOOOO 
   YOOOOOOOOOOOOOOOP
   `OOOOOI```IOOOOO'
    `OOOOI,,,IOOOO'
     `OOOOOOOOOOO'
       `~OOOOO~'